import sys

from PyQt5.QtWidgets import (
    QApplication, QDialog, QMainWindow, QMessageBox
)

from main_ui import Ui_enigma_board

class Window(QMainWindow, Ui_enigma_board):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        # self.connectSignalsSlots()

    # def connectSignalsSlots(self):
    #     self.action_Exit.triggered.connect(self.close)
    #     self.action_Find_Replace.triggered.connect(self.findAndReplace)
    #     self.action_About.triggered.connect(self.about)


app = QApplication(sys.argv)
win = Window()
win.show()
sys.exit(app.exec())

# this commande is for compiling the .ui file generated by the qt designer studio:
# pyuic5 -o main_ui.py ui/qt.ui
# when we finish the app, we can convert it to executable file using this commande:
# pyinstaller --onefile --windowed -i"C:\Users\Taki\Desktop\Code\Python\enigma\TP\ui\resources\enigma.ico" "C:\Users\Taki\Desktop\Code\Python\enigma\TP\app.py"