import sys
import time
from PyQt5 import QtGui
from PyQt5.QtWidgets import (
    QApplication, QMainWindow
)

from main_ui import Ui_enigma_board


class Window(QMainWindow, Ui_enigma_board):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        self.disableConfigs()
        # self.changeLetterColor("b","blue")
        # self.a.setStyleSheet("color: blue ")
        #--------------------
        self.configurerButton.clicked.connect(self.configurer_button_clicked)
        self.encrypterButton.clicked.connect(self.encypter_button_clicked)
        self.decrypterButton.clicked.connect(self.decrypter_button_clicked)
        self.suivantButton.clicked.connect(self.suivant_button_clicked)
        #--------------------

    def disableConfigs(self):
        self.c1_R.setEnabled(False)
        self.c1_DG.setEnabled(False)
        self.c1_box.setEnabled(False)
        self.c2_R.setEnabled(False)
        self.c2_DG.setEnabled(False)
        self.c2_box.setEnabled(False)
        self.c3_R.setEnabled(False)
        self.c3_DG.setEnabled(False)
        self.c3_box.setEnabled(False)

    def enableConfigs(self):
        self.c1_R.setEnabled(True)
        self.c1_DG.setEnabled(True)
        self.c1_box.setEnabled(True)
        self.c2_R.setEnabled(True)
        self.c2_DG.setEnabled(True)
        self.c2_box.setEnabled(True)
        self.c3_R.setEnabled(True)
        self.c3_DG.setEnabled(True)
        self.c3_box.setEnabled(True)

    def configurer_button_clicked(self):
        self.enableConfigs()

    def encypter_button_clicked(self):
        msg = self.encryptTextEdit.toPlainText()
        self.decryptTextEdit.setText(msg)

    def suivant_button_clicked(self):
        msg = self.encryptTextEdit.toPlainText()
        for c in msg:
            self.changeLetterColor(c, "red")

    def decrypter_button_clicked(self):
        pass

    def changeLetterColor(self, letter, color):
        getattr(self, letter).setAutoFillBackground(True)  # This is important!!
        # getattr(self,letter).setStyleSheet("QLabel { background-color: "+color+" }")
        getattr(self, letter).setStyleSheet("QLabel { color: "+color+" }")

app = QApplication(sys.argv)
win = Window()
win.show()
sys.exit(app.exec())

# this commande is for compiling the .ui file generated by the qt designer studio: pyuic5 -o main_ui.py ui/qt.ui when
# we finish the app, we can convert it to executable file using this commande: pyinstaller --onefile --windowed
# -i"C:\Users\Taki\Desktop\Code\Python\enigma\TP\ui\resources\enigma.ico"
# "C:\Users\Taki\Desktop\Code\Python\enigma\TP\app.py"
